openapi: 3.2.0
info:
  title: Example Submission and Suspension APIs
  # description: |-
  #   Example description
  # contact:
  #   email: email@example.org
  version: 0.1.0
# externalDocs:
#   description: Find out more about Swagger
#   url: https://swagger.io
tags:
  - name: Wikis
    # description: 
  - name: Review Submissions
    # description: 
  - name: Manual (Un)suspensions
    # description: 
paths:
  /wiki/{wiki_id}:
    get:
      tags:
        - Wikis
      parameters:
        - $ref: "#/components/parameters/WikiId"

  /wiki/{wiki_id}/review_submissions:
    get:
      tags:
        - Wikis
      summary: Get a Wiki's review submissions
      description: Returns an ordered list of review submissions.
      operationId: getWikiReviewSubmissions
      parameters:
        - $ref: "#/components/parameters/WikiId"

  /wiki/{wiki_id}/manual_suspensions:
    get:
      tags:
        - Wikis
      summary: Get a Wiki's manual suspensions
      operationId: getWikiManualSuspensions
      parameters:
        - $ref: "#/components/parameters/WikiId"
    post:
      tags:
        - Wikis
      summary: Create a manual suspension
      # description: 
      operationId: wikiCreateManualSuspension
      parameters:
        - $ref: "#/components/parameters/WikiId"
      requestBody: 
        content: 
          application/json: 
            schema: 
              type: object
              required:
                - reason
              properties:
                active_from:
                  type: 
                      - string
                      - 'null'
                  format: date-time
                active_until:
                  type: 
                      - string
                      - 'null'
                  format: date-time
                reason:
                  type: string
                  enum:
                    - tou_violation
                    - grace_period / temporary_extension
                    - other
      responses: 
        '200':
          description: The created manual suspension
          content: 
            application/json: 
              schema: 
                type: object
                properties: 
                  id:
                    type: integer
                    minimum: 1
                  wiki_id:
                    type: integer
                    minimum: 1
                  active_from:
                    type: string
                    format: date-time
                  active_until:
                    type: 
                      - string
                      - 'null'
                    format: date-time
                  reason:
                    type: string
                    enum:
                      - tou_violation
                      - grace_period / temporary_extension
                      - other

  /wiki/{wiki_id}/manual_unsuspensions:
    get:
      tags:
        - Wikis
      summary: Get a Wiki's manual unsuspensions
      operationId: getWikiManualSuspensions
      parameters:
        - $ref: "#/components/parameters/WikiId"
    post:
      tags:
        - Wikis
      summary: Create a manual unsuspension
      description: 
      operationId: wikiCreateManualUnsuspension
      parameters:
        - $ref: "#/components/parameters/WikiId"
      requestBody: 
        content: 
          application/json: 
            schema: 
              type: object
              required:
                - reason
              properties:
                active_from:
                  type: 
                      - string
                      - 'null'
                  format: date-time
                active_until:
                  type: 
                      - string
                      - 'null'
                  format: date-time
                reason:
                  type: string
                  enum:
                    - grace_period / temporary_extension
                    - other
      responses: 
        '200':
          description: The created manual unsuspension
          content: 
            application/json: 
              schema: 
                type: object
                properties: 
                  id:
                    type: integer
                    minimum: 1
                  wiki_id:
                    type: integer
                    minimum: 1
                  active_from:
                    type: string
                    format: date-time
                  active_until:
                    type: 
                      - string
                      - 'null'
                    format: date-time
                  reason:
                    type: string
                    enum:
                      - tou_violation
                      - other

  /review_submissions/{review_submission_id}:
    get:
      tags: 
        - Review Submissions
      summary: Get review submission by identifier
      description: Returns a single review submission.
      operationId: getReviewSubmissionById
      parameters:
        - $ref: "#/components/parameters/ReviewSubmissionId"
      responses:
        '200':
          description: A single Review Submission
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ReviewSubmission"
    put:
      tags: 
        - Review Submissions
      summary: Update an existing review submission
      description: Update an existing review submission by ID.
      operationId: updateReviewSubmissionById
      parameters:
        - $ref: "#/components/parameters/ReviewSubmissionId"
      requestBody: 
        $ref: "#/components/requestBodies/ReviewSubmission"
      responses:
        '200':
          description: A single Review Submission
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ReviewSubmission"
              example:
                  id: 1
                  additional_information: "string"
                  state: "approved"
                  "submitted_at": "2026-08-24T22:33:14.984Z"

  # /manual_suspensions:
  #   post:
  #     tags:
  #       - Manual (Un)suspensions
  #     summary: Create a manual suspension
  #     description:
  #     operationId: createManualSuspension
  #     requestBody: 
  #       content: 
  #         application/json: 
  #           schema: 
  #             type: object
  #             required: 
  #               - wiki_id
  #               - reason
  #             properties:
  #               wiki_id:
  #                 type: integer
  #                 minimum: 1
  #               active_from:
  #                 type: 
  #                     - string
  #                     - 'null'
  #                 format: date-time
  #               active_until:
  #                 type: 
  #                     - string
  #                     - 'null'
  #                 format: date-time
  #               reason:
  #                 type: string
  #                 enum:
  #                   - tou_violation
  #                   - grace_period / temporary_extension
  #                   - other
  #     responses: 
  #       '200':
  #         description: The created manual suspension
  #         content: 
  #           application/json: 
  #             schema: 
  #               type: object
  #               properties: 
  #                 id:
  #                   type: integer
  #                   minimum: 1
  #                 wiki_id:
  #                   type: integer
  #                   minimum: 1
  #                 active_from:
  #                   type: string
  #                   format: date-time
  #                 active_until:
  #                   type: 
  #                     - string
  #                     - 'null'
  #                   format: date-time
  #                 reason:
  #                   type: string
  #                   enum:
  #                     - tou_violation
  #                     - grace_period / temporary_extension
  #                     - other

  # /manual_unsuspensions:
    post:
      tags:
        - Manual (Un)suspensions
      summary: Create a manual unsuspension
      # description: 
      operationId: createManualUnsuspension
      requestBody: 
        content: 
          application/json: 
            schema: 
              type: object
              required: 
                - wiki_id
                - reason
              properties:
                wiki_id:
                  type: integer
                  minimum: 1
                active_from:
                  type: 
                      - string
                      - 'null'
                  format: date-time
                active_until:
                  type: 
                      - string
                      - 'null'
                  format: date-time
                reason:
                  type: string
                  enum:
                    - tou_violation
                    - grace_period / temporary_extension
                    - other
      responses: 
        '200':
          description: The created manual unsuspension
          content: 
            application/json: 
              schema: 
                type: object
                properties: 
                  id:
                    type: integer
                    minimum: 1
                  wiki_id:
                    type: integer
                    minimum: 1
                  active_from:
                    type: string
                    format: date-time
                  active_until:
                    type: 
                      - string
                      - 'null'
                    format: date-time
                  reason:
                    type: string
                    enum:
                      - tou_violation
                      - grace_period / temporary_extension
                      - other

components:
  parameters:
    WikiId:
      name: wiki_id
      in: path
      # description: 
      required: true
      schema:
        type: integer
        minimum: 1
    ReviewSubmissionId:
      name: review_submission_id
      in: path
      # description: 
      required: true
      schema: 
        type: integer
        minimum: 1

  requestBodies: 
    ReviewSubmission:
      content:
        application/json: 
          schema: 
            type: object
            properties:
              state:
                type: string
                enum:
                  - submitted
                  - review_started
                  - approved
                  - rejected
                  - cancelled
                example: "approved"

  schemas:
    ReviewSubmission:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        # wiki_id:
        #   type: integer
        #   minimum: 1
        additional_information:
          type: string
          description: The user-submitted additional information
        state:
          type: string
          enum:
            - submitted
            - review_started
            - approved
            - rejected
            - cancelled
        submitted_at:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
